version: '3.9'
services:

  mariadb:
    image: mariadb:5.5.49
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"  
    volumes:
      - mysql:/var/lib/mysql/
      - ./conf/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  traccar:
    image: traccar-preview:6.5
    container_name: traccar
    hostname: traccar
    restart: always
    ports:
      - "5000-5150:5000-5150"
      - "8082:8082"
    volumes:
      #- traccar-db:/opt/traccar/data/database
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml
      - ./short:/opt/traccar/templates/short
    depends_on:
      mariadb:
        condition: service_healthy

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    hostname: evolution-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution

volumes:
  postgres_data:
  evolution_instances:
  traccar-db:
  mysql: